config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def self.fetch_all_from_contentful
    client = Contentful::Client.new(
      space: 'kk2bw5ojx476',
      access_token: '7ac531648a1b5e1dab6c18b0979f822a5aad0fe5f1109829b8a197eb2be4b84c'
    )

    client.entries(content_type: 'recipe').each do |entry|
      create_or_update_from_contentful(entry)
    end
  end

  def self.create_or_update_from_contentful(entry)
    recipe = find_or_initialize_by(id: entry.id)
    recipe.title = entry.title
    recipe.image_url = 'https:' + entry.photo.url
    recipe.description = entry.description
    recipe.calories = entry.calories
    recipe.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = RecipesService::Index.call
  end

  def show
    @recipe = RecipesService::Show.call(params.require(:id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<%= yield %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<ul>
    <% @recipes.each do |recipe| %>
    <li>
        <%= link_to recipe['title'], recipe_path(recipe['id']) %>
        <% if recipe['image_url'].present? %>
        <%= image_tag recipe['image_url'] %>
        <% end %>
    </li>
    <% end %>
</ul>

app/views/recipes/show.html.erb
<h1><%= @recipe['title'] %></h1>
<% if @recipe['image_url'].present? %>
  <%= image_tag @recipe['image_url'] %>
<% end %>
<p><b>Description</b></p>
<p><%= @recipe['description'] %></p>
<p><b>Total Calories</b></p>
<p><%= @recipe['calories'] %></p>
<%= link_to 'Back to Recipes List', recipes_path, class: 'btn btn-primary' %>